"""
This script processes synthetic healthcare data generated by Synthea and transforms it into an ML-ready claims dataset.
It joins patient demographics, procedure data, and payer transitions to construct structured claim records and applies
realistic, rule-based logic to simulate denial flags and denial reasons.

Key steps:
- Load raw Synthea CSV files: patients, procedures, payer transitions
- Join data to associate procedures with patient and payer context
- Generate derived features (age, billed amount, claim_id, etc.)
- Apply modular denial rules to flag and categorize denials
- Export the final dataset to `data/sample_claims.csv`

This dataset is intended for training ML models in denial prediction, clustering root causes, and routing logic.

Note: All data is synthetic and HIPAA-compliant.
"""
import pandas as pd






